use CleanBee;
select * from Dustbin;
insert into Dustbin Values(12302, 'Public', 'Jayanagar');
select * from DustbinStatus;
insert into DustbinStatus Values(12302, 9, 123);
ALTER TABLE DustbinStatus ADD CONSTRAINT CHK_Status CHECK (Status >= 0);
ALTER TABLE DustbinStatus DROP CONSTRAINT CHK_Status;
ALTER TABLE DustbinStatus ADD CONSTRAINT CHK_Status CHECK (Status >= 0);
ALTER TABLE DustbinStatus ADD CONSTRAINT CHK_Status2 CHECK (Status <= 10);
insert into User Values('Megha', 'megha@gmail.com', 'bleh', 'DEF', 234);
insert into Dustbin Values(23403, 'Public', 'MG Road');
insert into DustbinStatus Values(23403, 2, 234);
select * from User;
select * from Dustbin;
ALTER TABLE Dustbin ADD CONSTRAINT CHK_Status3 CHECK (DustbinType in ('Public','Private'));
select * from User;
delete from DustbinStatus where DustbinCode;
delete from Dustbin where DustbinCode;
SET SQL_SAFE_UPDATES=0;
update DustbinStatus set Status=9 where DustbinCode=12303;
alter table DustbinStatus add foreign key(DustbinCode) references Dustbin(DustbinCode);
